### ISSUE TITLE
python3 pop_align.py AssertionError: Failed in nopython mode pipeline (step: nopython rewrites) key already in dictionary: 'index.5'

### ISSUE THREAD

**Issue by pong1013** [sweetcocoa/pop2piano#16]
When I running pop_align.py , met the error below:

``` joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "pop_align.py", line 57, in save_delayed_song
    rd = get_aligned_results(midi_pm=midi_pm, song_audio=song_audio)
  File "pop_align.py", line 127, in get_aligned_results
    opt_chroma_shift = compute_optimal_chroma_shift(
  File "/home/justin/.local/lib/python3.8/site-packages/synctoolbox/dtw/utils.py", line 47, in compute_optimal_chroma_shift
    D, _, _ = compute_warping_path(cost_matrix_tmp, step_sizes=step_sizes, step_weights=step_weights)
  File "/home/justin/.local/lib/python3.8/site-packages/synctoolbox/dtw/core.py", line 196, in compute_warping_path
    wp = __E_to_warping_path(E=E,
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 240, in run_pass
    rewrites.rewrite_registry.apply('after-inference', state)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/rewrites/registry.py", line 67, in apply
    matches = rewrite.match(state.func_ir, block, state.typemap,
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/inline_closurecall.py", line 1347, in match
    self.new_body = guard(_inline_const_arraycall, block, func_ir,
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/ir_utils.py", line 1527, in guard
    return func(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/inline_closurecall.py", line 1517, in _inline_const_arraycall
    if guard(inline_array, inst.target, expr,
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/ir_utils.py", line 1527, in guard
    return func(*args, **kwargs)
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/inline_closurecall.py", line 1448, in inline_array
    typemap[index_var.name] = index_typ
  File "/home/justin/.local/lib/python3.8/site-packages/numba/core/utils.py", line 375, in __setitem__
    raise AssertionError("key already in dictionary: %r" % (key,))
AssertionError: Failed in nopython mode pipeline (step: nopython rewrites)
key already in dictionary: 'index.5'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pop_align.py", line 331, in <module>
    main(samples=samples, dry_run=args.dry_run)
  File "pop_align.py", line 285, in main
    Parallel(n_jobs=multiprocessing.cpu_count() // 2)(
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/justin/.local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
AssertionError: Failed in nopython mode pipeline (step: nopython rewrites)
key already in dictionary: 'index.5'

**Comment by pong1013** [comment]
I downgrading numba to 0.51.0 to solve this error.
